implemented pagination, sorting, swagger
Sasha-Bachynskyi/online-book-store pull request #6
Opened 2023-11-06 13:49 UTC by Sasha-Bachynskyi

2023-11-14 14:35 UTC, yevheniisynytsia requested changes
optional comment, but nice to have =)

2023-11-14 14:35 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/controller/BookController.java
>      public BookDto save(@RequestBody @Valid BookRequestDto requestDto) {
I would also go further and used `@Parameter` for parameters and `@Schema` (for dtos)

2023-11-16 10:20 UTC, Sasha-Bachynskyi commented on src/main/java/com/onlinebookstore/controller/BookController.java
>      public BookDto save(@RequestBody @Valid BookRequestDto requestDto) {
It's not necessary, swagger adds parameters and schema in any case

2023-11-21 10:22 UTC, yevheniisynytsia approved these changes

2023-11-22 13:42 UTC, merged