implemented spring security
Sasha-Bachynskyi/online-book-store pull request #7
Opened 2023-11-12 10:15 UTC by Sasha-Bachynskyi

2023-11-15 12:49 UTC, yevheniisynytsia requested changes
Well done! Let's improve the solution a bit

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/controller/AuthenticationController.java
> +public class AuthenticationController {
I would recommend adding swagger here with all the info that can be helpful to authenticate. ex: schema of dto using `@Schema`

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/model/Role.java
> +@Setter
I would recommend using just `@Data` to make it simple for you and to prevent possible issues with equals, hashcode in future

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/model/User.java
> +@SQLDelete(sql = "UPDATE users SET is_deleted = true Where id=?")
```suggestion
@SQLDelete(sql = "UPDATE users SET is_deleted = true WHERE id=?")
```

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/model/User.java
> +@Setter
let's go with `@Data`

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/model/User.java
> +
If you add `@Data` then exclude this filed from equals, hashcode and toString

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.LAZY)
wouldn't `EAGER` be better for roles?

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/repository/user/UserRepository.java
> +    @EntityGraph(attributePaths = "roles")
not sure if this will work with `FetchType.LAZY`, have you tested this?

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/service/user/UserServiceImpl.java
> +            throw new RegistrationException("Unable to complete registration");
let's add more informative error message
we know the same email is registered - let the user know

2023-11-15 12:49 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/service/user/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
I was thinking of moving this service into `AuthenticationService` as they are related, but I'll let you choose. This is also nice

2023-11-16 10:28 UTC, Sasha-Bachynskyi commented on src/main/java/com/onlinebookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.LAZY)
Isn't it the best practice to keep it `LAZY` here?

2023-11-16 10:30 UTC, Sasha-Bachynskyi commented on src/main/java/com/onlinebookstore/repository/user/UserRepository.java
> +    @EntityGraph(attributePaths = "roles")
It works fine, I have tested it. Haven't you used this annotation?)

2023-11-16 10:32 UTC, Sasha-Bachynskyi commented on src/main/java/com/onlinebookstore/service/user/UserServiceImpl.java
> +            throw new RegistrationException("Unable to complete registration");
Sure thing)

2023-11-16 10:36 UTC, Sasha-Bachynskyi commented on src/main/java/com/onlinebookstore/service/user/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
I'll keep them separate

2023-11-21 10:50 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.LAZY)
I would say it depends on the situation, but lazy is also ok =)

2023-11-21 10:51 UTC, yevheniisynytsia approved these changes

2023-11-22 14:02 UTC, merged